### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by tong1101** [AceCoooool/segmentation#1]
2019-05-20 19:45:05,286 Segmentation INFO: Start training, total epochs 120 = total iteration: 178440
Traceback (most recent call last):
         File "<ipython-input-1-c9d0c56cac10>", line 1, in <module>
runfile('/home/ydc/tl/pytorch/segmentation-master/train_segmentation.py', wdir='/home/ydc/tl/pytorch/segmentation-master')
         File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
execfile(filename, namespace)
         File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
exec(compile(f.read(), filename, 'exec'), namespace)
         File "/home/ydc/tl/pytorch/segmentation-master/train_segmentation.py", line 315, in <module>trainer.training()
         File "/home/ydc/tl/pytorch/segmentation-master/train_segmentation.py", line 214, in training
outputs = self.net(image)
         File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
result = self.forward(*input, **kwargs)
         File "/home/ydc/tl/pytorch/segmentation-master/model/seg_models/danet.py", line 132, in forward
    x = self.head(c4)
         File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__result = self.forward(*input, **kwargs)
         File "/home/ydc/tl/pytorch/segmentation-master/model/seg_models/danet.py", line 101, in forward 
    sa_feat = self.sa(feat1)
         File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__result = self.forward(*input, **kwargs)
         File "/home/ydc/tl/pytorch/segmentation-master/model/seg_models/danet.py", line 35, in forward
    energy = torch.bmm(proj_query, proj_key)

RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653183467/work/aten/src/THC/THCBlas.cu:450

The problem is the mismatch between the driver version and cuda version ?
My env is：
python 3.6
pytorch 1.1.0
cudatoolkit 9.0
cudnn 7.3.1
Or pytorch version problem？

**Comment by tong1101** [comment]
I find it runs randomly after I run it many times.What's the problem?
